name: Python Application



on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Install dependencies
        run: |
          make install

      - name: Execute test cases
        run: |
          pytest test.py
